import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lucas Zarandón',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />

        <meta property="og:title" content="Lucas Zarandón" />
        <meta property="og:description"
          content="Soy Lucas Zarandón, Docente y Desarrollador Web Front-end con experiencia en diseño, IA y desarrollo de videojuegos" />
        <meta property="og:image" content="https://raw.githubusercontent.com/lucaszhh/my-portfolio/main/public/icon.webp" />
        <meta property="og:url" content="https://lucaszarandon.vercel.app/" />
        <meta property="og:type" content="website" />

      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
